#### Numpy


# ndarray #### List data type 

In [1]:
#! pip install numpy

In [ ]:
# ! conda install numpy

In [12]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(f"Type: {type(arr)}")
print(f"Shape: {arr.shape}") #attr
print(f"Size: {arr.size}") #attr
print(f"Dimention: {arr.ndim}") #attr
print(dir(arr))

[1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Size: 5
Dimention: 1
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '

In [ ]:
import time

py_list = list(range(1000000)) #range builtin datatype 
np_array = np.arange(1000000)

start = time.time()
sum_py = sum(py_list)
end = time.time()
print(f"Python list sum:{sum_py}, Time: {end - start}")

start = time.time()
sum_np = np.sum(np_array)
end = time.time()
print(f"Numpy array sum:{sum_np}, Time: {end - start}")

Python list sum:499999500000, Time: 0.005289793014526367
Numpy array sum:499999500000, Time: 0.0006780624389648438


In [ ]:
arr2 = np.array([[1,2,3],
                [4,5,6]])
arr2.shape
arr2.size
arr2.ndim
arr2.dtype

# 10.0000000000099 #64 -> 16 
# 10.000099 #32 

dtype('int64')

In [32]:
np.arange(0,10,2) #start, stop, step
# for i in range(0,10,2):
#     print(i)

array([0, 2, 4, 6, 8])

In [40]:
np.linspace(0,1,10) 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [44]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [45]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
x = np.array([1.2,2.3,5.1])
x.dtype
x.astype(int).dtype

dtype('int64')

In [63]:
arr = np.arange(1,13)
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [68]:
arr = np.array([10,20,30,40,50])
#indexing
arr[0]
arr[-1]
arr[1:4]
arr[3:]
arr[::2] #every 2 element

array([10, 30, 50])

In [86]:
arr = np.arange(0,10).reshape(2,5)
arr[0][2]
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concat = np.concatenate((arr1, arr2))
vstack = np.vstack((arr1, arr2))
hstack = np.hstack((arr1, arr2))

print("Concatenate:", concat)
print("Vertical Stack:\n", vstack)
print("Horizontal Stack:", hstack)

Concatenate: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack: [1 2 3 4 5 6]


In [ ]:
۱. یک آرایه ۳×۳ با اعداد تصادفی بین ۱ تا ۱۰ بسازید.
۲. نوع داده‌ی آن را بررسی کنید.
۳. آن را به عدد صحیح (float) تبدیل کنید.
۴. تعداد بعد و شکل آن را چاپ کنید.
